### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by TheLastBilly** [AndrewPiroli/ppcskel#1]
Sorry, I didn't know how else to contact you but I wanted to thank you for taking the time to write the build script for the powerpc-none-elf toolchain, you are an absolute life-saver! I'm doing some experimentation/research on the Wii and I've been trying to come up with ways to build ppcskel and gumboot for a couple days now

**Comment by AndrewPiroli** [comment]
You're welcome. I made it for testing after I found a few bugged versions of GCC. Glad it could be useful.
